[package]
name = "rumiga-core"
description = "Amiga emulation core — CPU, chipset, memory, timing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[features]
default = ["std"]
std = ["m68k/std", "m68k/fpu"]
no_std = ["m68k/no_std"]

[dependencies]
m68k = { workspace = true }
rumiga-platform = { workspace = true }

[dev-dependencies]
m68000 = { workspace = true }
stats_alloc = { workspace = true }

[lints]
workspace = true
