[workspace]
resolver = "3"
members = [
    "crates/rumiga-core",
    "crates/rumiga-platform",
    "crates/rumiga-platform-desktop",
    "crates/rumiga-api",
    "crates/m68000",
    "desktop",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/metaneutrons/rumiga"
rust-version = "1.85.0"
readme = "README.md"
keywords = ["amiga", "emulator", "esp32", "retro", "m68k"]
categories = ["emulators"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
