[package]
name = "rumiga-api"
description = "Shared REST API types for the Rumiga emulator"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["alloc"] }

[lints]
workspace = true
