[package]
name = "rumiga-platform-esp"
description = "ESP-IDF platform backend for the Rumiga emulator (reTerminal D1001)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
rumiga-platform = { workspace = true }

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-svc = { workspace = true, features = ["std"] }

[lints]
workspace = true
