[alias]
xtask = "run --locked --package rumiga-xtask --"

[target.riscv32imafc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true, force = true }
ESP_IDF_REPOSITORY = { value = "https://github.com/espressif/esp-idf.git", force = true }
ESP_IDF_SDKCONFIG = { value = "firmware/sdkconfig", relative = true, force = true }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "firmware/sdkconfig.defaults", relative = true, force = true }
ESP_IDF_SYS_ROOT_CRATE = { value = "rumiga-firmware", force = true }
ESP_IDF_TOOLS_INSTALL_DIR = { value = "workspace", force = true }
ESP_IDF_VERSION = { value = "tag:v6.0", force = true }
MCU = { value = "esp32p4", force = true }
