[package]
name = "rumiga-firmware"
description = "Rumiga Amiga emulator firmware for reTerminal D1001"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
rumiga-core = { workspace = true }
rumiga-platform = { workspace = true }
rumiga-platform-esp = { workspace = true }

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-svc = { workspace = true, features = ["binstart", "std"] }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }

[build-dependencies]
embuild = { workspace = true, features = ["espidf"] }

[lints]
workspace = true
