[package]
name = "rumiga-desktop"
description = "Rumiga Amiga emulator — desktop binary for development"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
minifb = { workspace = true }
m68k = { workspace = true, features = ["std", "fpu"] }
png = "0.17"
rumiga-core = { workspace = true }
rumiga-platform = { workspace = true }
rumiga-platform-desktop = { workspace = true }
rumiga-api = { workspace = true }
sha2 = { workspace = true }
axum = { version = "0.8", features = ["macros", "multipart", "json"] }
tokio = { version = "1.52", features = ["full"] }
rust-embed = "8.11"
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
core_affinity = { workspace = true }
fs2 = "0.4.3"
libslirp = { version = "4.3.2", default-features = false }
mio = "1.2.1"

[lints]
workspace = true
